service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8888
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: main_store

  jaeger_storage:
    backends:
      main_store:
        badger:
          directories:
            keys: "/tmp/sidequest-jaeger/keys"
            values: "/tmp/sidequest-jaeger/values"
          ephemeral: false
          ttl:
            spans: 168h

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: main_store
